lugares = ['china','japão','canada']
print(lugares)
print('Com o comando sorted')
print(sorted(lugares))
print('Com o comando sorted novamente, que vai inverter a lista')
print(sorted(lugares))
print('Com o método reverse')
lugares.reverse()
print(lugares)
lugares.reverse()
print(lugares)
print('Com o comand o sort')
lugares.sort()
print(lugares)
lugares.sort()
print(lugares)
